### PR TITLE
feat(proxy): allowing module users to specify egress proxy settings

### PR DESCRIPTION
**Pull request by calvo2024**
## Description
Variables *http_proxy*, *https_proxy* and *additional_no_proxy* have been added to the module, allowing it to enforce egress traffic to go through a forward proxy.

## Related issue
N/A

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How has this been tested?
1. Deploy a squid proxy within the prerequisites network.
2. For each container runtime (docker, podman) deploy the module with and without enforcing egress traffic to go through the proxy.

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by roooms** [comment]
@alexbasista please consider this along with your planned updates for the next release.

**Review by jkellner-hashi — APPROVED** [review]
I tested this and it looks good. From my perspective, it should be merged.

Test cases:
`examples/podman-rhel-internal-nlb`: Tested with Podman and RHEL9
curl works from TFE VM and from within TFE container
user data script completes successfully
`tfectl app status` shows all green
TFE functionality works. Can create workspaces, run apply, VCS connection works

`examples/docker-ubuntu-internal-nlb`: Tested with Docker and Ubuntu
curl works from TFE VM and from within TFE container
user data script completes successfully
`tfectl app status` shows all green
TFE functionality works. Can create workspaces, run apply, VCS connection works

**Comment by alexbasista** [comment]
RDS, S3, and Redis endpoints need to be dynamically added to `no_proxy` before this is complete.

**Comment by roooms** [comment]
Adding @calvo2024 as an assignee to consider feedback from @alexbasista and way forward.

**Review by jkellner-hashi — APPROVED** [review]

**Review by alexbasista — APPROVED** [review]

**Pull request merged**
